# Generated by Django 5.1.3 on 2024-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
