# Generated by Django 5.1.3 on 2024-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_formmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='file',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
    ]
